### ISSUE TITLE
ElCom UI use cases

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#1]
Hi! As promised, here's a (incomplete) list of use cases we need to cover. I don't expect everything to be handled by this library but either way we need a solution (even if it's raw SPARQL).

1. Queries to get a list of all municipalities/cantons/providers/products/… _including labels_, a.k.a [component values](https://zazuko.github.io/query-rdf-data-cube/classes/datacube.html#componentvalues)
  a. the same lists but filtered by matching a label (ideally translated)
  b. the same lists but filtered by other dimensions (e.g. by year). This would probably be a filter on the observations, then get all DISTINCT values for each dimension?
2. Given a municipality/canton/provider a query to get all connected municipality/canton/providers.
  a. E.g. for Stadt Zürich I want to get Canton (Zürich) and provider(s) (ewz, …)
3. All observations for a certain municipality/canton/provider, filtered by other dimensions (year etc.) 👈 I think this should be covered by existing API and examples.

@ktk I assume that each observation has municipality, canton, and provider as a dimension?

**Comment by ktk** [comment]
@herrstucki no the canton won't be attached to the observation, this is done via nesting of municipality. That can be queried via the view-concept, we will provide an example.
