### ISSUE TITLE
Filters on source.cubes()

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#19]
Is it possible to apply filters to `source.cubes()`?

Cf. https://github.com/zazuko/rdf-cube-schema-viz/issues/1#issuecomment-744521444

**Comment by bergos** [comment]
@herrstucki I created a PR. It includes an example for publish status and versioning: https://github.com/zazuko/rdf-cube-view-query/pull/27/files#diff-39d012147d0ee2714f2941e7518c47dc8ef854dd097bf4a0121885fafc4c6892

**Comment by bergos** [comment]
@herrstucki I merged #27 to have the first filters already in a release. Other filters, including regex, could be added. Can we collect use cases, so I can add them in a single batch? Besides the generic filter functions we should also think about cases where a shortcut makes sense. For example schema:name could be added like `Cube.filter.name('A.*')`.

**Comment by bergos** [comment]
I will close this issue. Specific filters have now their own issue #31 #32 .
