### ISSUE TITLE
Listing all cubes without querying the shape

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#37]
When using `source.cubes()` all cubes are initialized including the shape. For some cubes, the shape query is quite slow.

For listing the cubes, it would be great if there were a method to query the cubes including their metadata but without running the shape query. Running the shape query could then be done in a second step, once a cube is selected from the list.

**Comment by l00mi** [comment]
@herrstucki would that be what you need? https://github.com/zazuko/rdf-cube-view-query/pull/53

**Comment by bergos** [comment]
solved in v1.4.0
