### ISSUE TITLE
Query filter which should return no observations still returns 1 empty observation

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#4]
The following query https://s.zazuko.com/9CXT9 should return 0 results but still will return there's an empty one.

When I remove the GROUP BY it works.

**Comment by ktk** [comment]
Huh that is very strange. It also does not seem to related to the URI, you can enter whatever you want there and with GROUP BY it gives something back. I will ask Stardog if I get something wrong here or if this is a bug.

**Comment by ktk** [comment]
Got some feedback from Stardog:

>In SPARQL aggregation over the empty result set returns a single result with unbound variables. There's a DAWG test specifically for that (called ":agg-empty-group2", cf. https://www.w3.org/2009/sparql/meeting/2012-10-30#resolution_2). The following query:
>
>```sparql
>SELECT ?x (MAX(?value) AS ?max)
>WHERE {
>
>?x ex:p ?value
>
>} GROUP BY ?x
>```
>
>returns a single result with unbound ?x and ?max when evaluated over the empty data. In Stardog, this behaviour does not depend on whether there's an explicit GROUP BY or not (i.e. aggregation over all variables).
>
>This is a bit of a grey area in the spec and has been recently discussed at https://github.com/eclipse/rdf4j/issues/1978. There's a chance the behaviour will change in SPARQL 1.2. Until now we suggest to use HAVING to filter our the empty group.

**Comment by herrstucki** [comment]
Thanks! IMO the empty result should be filtered out by this library then. Otherwise it can lead to quite unexpected outcomes on the end user side (I‘m now filtering this myself).

**Comment by ktk** [comment]
FYI asked where we have an aggregation here, because there is no `SUM` or alike:

> Yeah, but you have `GROUP BY` which you can view as a degenerate case of aggregation (where groups are computed but aggregation is a no-op).
>
> Btw, having `DISTINCT` in a query with `GROUP BY` is unnecessary, grouped keys are always unique. If there're no aggregate functions but there's `GROUP BY`, the behaviour is basically `DISTINCT` except for this empty group thing.

**Comment by bergos** [comment]
Fixed in https://github.com/zazuko/sparql-http-client/commit/771918cada73863a227c5b6497ef42cfaecffd18
