### ISSUE TITLE
Use POST queries for large queries

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#40]
I can't find a way to override the sparq-http-client `operation` to [use POST](https://zazuko.github.io/sparql-http-client/#/?id=operation). Some [generated queries](https://int.lindas.admin.ch/sparql/#query=SELECT+DISTINCT+%3Fdimension0+%3Fdimension1+%3Fdimension2+%3Fdimension3+%3Fdimension4+%3Fdimension5+%3Fdimension6+%3Fdimension7+%3Fdimension8+%3Fdimension9+%3Fdimension10+%3Fdimension11+%3Fdimension12+%3Fdimension13+%3Fdimension14+%3Fdimension15+%3Fdimension16+%3Fdimension17+%3Fdimension18+%3Fdimension19+%3Fdimension20+%3Fdimension21+%3Fdimension22+%3Fdimension23+%3Fdimension24+%3Fdimension25+%3Fdimension26+%3Fdimension27+%3Fdimension28+%3Fdimension29+%3Fdimension30+%3Fdimension31+WHERE+%7B+++GRAPH+%3Chttps%3A%2F%2Flindas.admin.ch%2Ffoen%2Fcube%3E+%7B++++++%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2F2%2F%3E+%3Chttps%3A%2F%2Fcube.link%2FobservationSet%3E+%3FobservationSet0+.+++++%3FobservationSet0+%3Chttps%3A%2F%2Fcube.link%2Fobservation%3E+%3Fsource0+.+++++%3Fsource0+%3Chttp%3A%2F%2Fschema.org%2Fidentifier%3E+%3Fdimension0+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fjahr%3E+%3Fdimension1+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fschadstoffschwelle%3E+%3Fdimension2+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fmethode%3E+%3Fdimension3+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Finland%3E+%3Fdimension4+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fwert%3E+%3Fdimension5+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fbetrieb%3E+%3Fdimension6+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fdatenerhebung%3E+%3Fdimension7+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Finhaberin%3E+%3Fdimension8+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fkanton%3E+%3Fdimension9+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fland%3E+%3Fdimension10+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fmedium%3E+%3Fdimension11+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fquelle%3E+%3Fdimension12+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fschadstoff%3E+%3Fdimension13+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fschadstoff-gruppe%3E+%3Fdimension14+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fverwendung%3E+%3Fdimension15+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fsonderabfall%3E+%3Fdimension16+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fhaupttaetigkeit%3E+%3Fdimension17+.+++++%3Fsource0+%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD0001-Test-03%2Fabfallverwerter%3E+%3Fdimension18+.++++%7D+++OPTIONAL+%7B+++++%3Fdimension6+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension19_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension19_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension6+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension19_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension19_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension6+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension19_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension19_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension6+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension19_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension19_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension6+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension19_4+.+++++FILTER+(+++++++(LANG(%3Fdimension19_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension19_0%2C+%3Fdimension19_1%2C+%3Fdimension19_2%2C+%3Fdimension19_3%2C+%3Fdimension19_4)+AS+%3Fdimension19)+++OPTIONAL+%7B+++++%3Fdimension7+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension20_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension20_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension7+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension20_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension20_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension7+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension20_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension20_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension7+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension20_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension20_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension7+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension20_4+.+++++FILTER+(+++++++(LANG(%3Fdimension20_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension20_0%2C+%3Fdimension20_1%2C+%3Fdimension20_2%2C+%3Fdimension20_3%2C+%3Fdimension20_4)+AS+%3Fdimension20)+++OPTIONAL+%7B+++++%3Fdimension8+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension21_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension21_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension8+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension21_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension21_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension8+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension21_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension21_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension8+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension21_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension21_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension8+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension21_4+.+++++FILTER+(+++++++(LANG(%3Fdimension21_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension21_0%2C+%3Fdimension21_1%2C+%3Fdimension21_2%2C+%3Fdimension21_3%2C+%3Fdimension21_4)+AS+%3Fdimension21)+++OPTIONAL+%7B+++++%3Fdimension9+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension22_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension22_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension9+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension22_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension22_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension9+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension22_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension22_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension9+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension22_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension22_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension9+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension22_4+.+++++FILTER+(+++++++(LANG(%3Fdimension22_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension22_0%2C+%3Fdimension22_1%2C+%3Fdimension22_2%2C+%3Fdimension22_3%2C+%3Fdimension22_4)+AS+%3Fdimension22)+++OPTIONAL+%7B+++++%3Fdimension10+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension23_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension23_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension10+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension23_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension23_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension10+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension23_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension23_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension10+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension23_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension23_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension10+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension23_4+.+++++FILTER+(+++++++(LANG(%3Fdimension23_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension23_0%2C+%3Fdimension23_1%2C+%3Fdimension23_2%2C+%3Fdimension23_3%2C+%3Fdimension23_4)+AS+%3Fdimension23)+++OPTIONAL+%7B+++++%3Fdimension11+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension24_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension24_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension11+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension24_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension24_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension11+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension24_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension24_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension11+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension24_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension24_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension11+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension24_4+.+++++FILTER+(+++++++(LANG(%3Fdimension24_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension24_0%2C+%3Fdimension24_1%2C+%3Fdimension24_2%2C+%3Fdimension24_3%2C+%3Fdimension24_4)+AS+%3Fdimension24)+++OPTIONAL+%7B+++++%3Fdimension12+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension25_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension25_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension12+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension25_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension25_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension12+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension25_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension25_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension12+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension25_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension25_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension12+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension25_4+.+++++FILTER+(+++++++(LANG(%3Fdimension25_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension25_0%2C+%3Fdimension25_1%2C+%3Fdimension25_2%2C+%3Fdimension25_3%2C+%3Fdimension25_4)+AS+%3Fdimension25)+++OPTIONAL+%7B+++++%3Fdimension13+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension26_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension26_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension13+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension26_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension26_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension13+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension26_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension26_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension13+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension26_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension26_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension13+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension26_4+.+++++FILTER+(+++++++(LANG(%3Fdimension26_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension26_0%2C+%3Fdimension26_1%2C+%3Fdimension26_2%2C+%3Fdimension26_3%2C+%3Fdimension26_4)+AS+%3Fdimension26)+++OPTIONAL+%7B+++++%3Fdimension14+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension27_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension27_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension14+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension27_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension27_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension14+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension27_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension27_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension14+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension27_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension27_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension14+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension27_4+.+++++FILTER+(+++++++(LANG(%3Fdimension27_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension27_0%2C+%3Fdimension27_1%2C+%3Fdimension27_2%2C+%3Fdimension27_3%2C+%3Fdimension27_4)+AS+%3Fdimension27)+++OPTIONAL+%7B+++++%3Fdimension15+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension28_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension28_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension15+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension28_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension28_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension15+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension28_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension28_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension15+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension28_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension28_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension15+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension28_4+.+++++FILTER+(+++++++(LANG(%3Fdimension28_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension28_0%2C+%3Fdimension28_1%2C+%3Fdimension28_2%2C+%3Fdimension28_3%2C+%3Fdimension28_4)+AS+%3Fdimension28)+++OPTIONAL+%7B+++++%3Fdimension16+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension29_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension29_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension16+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension29_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension29_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension16+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension29_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension29_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension16+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension29_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension29_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension16+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension29_4+.+++++FILTER+(+++++++(LANG(%3Fdimension29_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension29_0%2C+%3Fdimension29_1%2C+%3Fdimension29_2%2C+%3Fdimension29_3%2C+%3Fdimension29_4)+AS+%3Fdimension29)+++OPTIONAL+%7B+++++%3Fdimension17+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension30_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension30_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension17+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension30_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension30_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension17+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension30_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension30_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension17+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension30_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension30_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension17+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension30_4+.+++++FILTER+(+++++++(LANG(%3Fdimension30_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension30_0%2C+%3Fdimension30_1%2C+%3Fdimension30_2%2C+%3Fdimension30_3%2C+%3Fdimension30_4)+AS+%3Fdimension30)+++OPTIONAL+%7B+++++%3Fdimension18+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension31_0+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension31_0)%2C+'de')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension18+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension31_1+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension31_1)%2C+'fr')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension18+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension31_2+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension31_2)%2C+'it')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension18+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension31_3+.+++++FILTER+(+++++++LANGMATCHES(LANG(%3Fdimension31_3)%2C+'en')+++++)+++%7D+++OPTIONAL+%7B+++++%3Fdimension18+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fdimension31_4+.+++++FILTER+(+++++++(LANG(%3Fdimension31_4)+%3D+'')+++++)+++%7D+++BIND(COALESCE(%3Fdimension31_0%2C+%3Fdimension31_1%2C+%3Fdimension31_2%2C+%3Fdimension31_3%2C+%3Fdimension31_4)+AS+%3Fdimension31)+%7D+GROUP+BY+%3Fdimension0+%3Fdimension1+%3Fdimension2+%3Fdimension3+%3Fdimension4+%3Fdimension5+%3Fdimension6+%3Fdimension7+%3Fdimension8+%3Fdimension9+%3Fdimension10+%3Fdimension11+%3Fdimension12+%3Fdimension13+%3Fdimension14+%3Fdimension15+%3Fdimension16+%3Fdimension17+%3Fdimension18+%3Fdimension19+%3Fdimension20+%3Fdimension21+%3Fdimension22+%3Fdimension23+%3Fdimension24+%3Fdimension25+%3Fdimension26+%3Fdimension27+%3Fdimension28+%3Fdimension29+%3Fdimension30+%3Fdimension31+LIMIT+10&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&requestMethod=POST&tabTitle=Query+3&headers=%7B%7D&outputFormat=table) are too large for GET.

Probably just using POST by default would be a good idea? Or as an option on `new Source()`?

**Comment by bergos** [comment]
fixed in #44 released as v1.3.0
