### ISSUE TITLE
Add version cube filter

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#42]
It should be possible to filter by version (eq, lt, gt etc.)

Currently, I'm doing this myself:

```js
({ cube, index }) => {
      const variable = rdf.variable(`version${index}`);
      return [
        [cube, ns.schema.version, variable],
        sparql`FILTER(${variable} > ${version})`,
      ];
    },
```

**Comment by bergos** [comment]
The latest version added this feature. An example can be found [here](https://github.com/zazuko/rdf-cube-view-query/blob/master/examples/lindas-cube-version.js).
