### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by ptbrowne** [zazuko/rdf-cube-view-query#61]
Since we work with typescript in visualize admin, we defined typescript definitions for the rdf-cube-view-query types. Would you be open to integrate them in here ?

Here they are : 

https://github.com/visualize-admin/visualization-tool/blob/main/app/typings/rdf.d.ts

Since we wrote them manually, some types/attributes are missing (for example Cube.filters types lack "in", "patternIn" etc.. I expect that if they are managed in this repository, they would be extracted automatically by Typescript and would not be incomplete.

**Comment by bergos** [comment]
I'm not a big TypeScript fan, but I see the value in having the definitions in a central place to make them reusable. My concern regarding adding the definitions to this repository is that once it's added, I'm doomed to take care of it and deal with all the issues regarding the definitions. That happened to me before. I would propose to create a separate repository. Would that be OK for you?

**Comment by ptbrowne** [comment]
The problem with having them in another repository is that it would be easier for the definitions to drift from the original implementation.

**Comment by tpluscode** [comment]
The types will drift apart anyway if they are not generated from the original source

We have some incomplete types in cube creator too but I gradually move any such local definitions to DefinitelyTyped. I propose we do the same

**Comment by tpluscode** [comment]
Alternatively, we could try adding comprehensive JSDoc and extracting types with `tsc --allowJs --declarationsOnly` but I have not tried that before

**Comment by ptbrowne** [comment]
Thanks for the response. I would be OK for moving our definitions to definitely typed, but clearly I'd prefer if the definitions were generated from the code.

> Alternatively, we could try adding comprehensive JSDoc

I've already done that in another project and it worked well.

I could move our definitions to DefinitelyTyped next week.

**Comment by l00mi** [comment]
Lets move as discussed to DefinitelyTyped for now. @bergos is it okay wit you to make a note in the Readme about their availability?
