### ISSUE TITLE
Improve performance for preview of cubes.

### ISSUE THREAD

**Issue by l00mi** [zazuko/rdf-cube-view-query#64]
Based on https://github.com/zazuko/cube-creator/issues/828 and [internal discussion](https://zulip.zazuko.com/#narrow/stream/54-bafu-cube-creator/topic/cube.20query/near/231834 ), a possibility to have a first cube preview without any restrictions is a wanted feature.

The goal should be the creation of a SPARQL query which is not using DISTINCT nor GROUP.

**Comment by bergos** [comment]
implemented in #69
