### ISSUE TITLE
Add an option to disable dimension sorting in View.fromCube

### ISSUE THREAD

**Issue by bprusinowski** [zazuko/rdf-cube-view-query#95]
Hey!

Recently I've been working on performance improvements in Visualize.admin and I've been looking at the performance of the data fetching. I've noticed that in some cases it takes much longer to create the `View` (`View.fromCube`) than to fetch the data itself – see the Comments section of [this PR](https://github.com/visualize-admin/visualization-tool/pull/1031).

It turned out that it's "slow" because the [dimensions are sorted by name](https://github.com/zazuko/rdf-cube-view-query/blob/355848747e5cf78886bbda2e41134976fb0f5f83/lib/View.js#L197C1-L206) when the View is created. I wanted to ask if it's necessary to sort them or if it's possible to add an option to enable / disable sorting?

I've made some tests and it seems that there was no impact on the generated observations query when adding such parameter (additionally, in Visualize we sort the observations and dimensions anyway in the front-end part). I would be happy to open a PR if this change makes sense :)

**Comment by Rdataflow** [comment]
@dabo505 can you put this issue on the fast track? we depend on this performance improvement for the next release of visualize...

**Comment by tpluscode** [comment]
By all means, do not hesitate to send a PR. Maybe with some additional examples because I do not yet fully understand the impact and where the actual time penalty occurs

**Comment by bprusinowski** [comment]
Sure, this is the benchmark I've made to pin-point the issue.

**With sorting enabled** (see that `--sort` took 549 ms and in total it took 556 ms). Generally it fluctuates around 500-600 ms in the example used for testing (this chart https://int.visualize.admin.ch/en/v/hKkUyBpGpWPl?dataSource=Int).

<img width="601" alt="with sorting" src="https://github.com/zazuko/rdf-cube-view-query/assets/52032047/012daee8-d9b9-439b-9716-60613977c72b">


**With sorting disabled** (see that in total it took 8 ms).

<img width="610" alt="without sorting" src="https://github.com/zazuko/rdf-cube-view-query/assets/52032047/e361badf-89ed-4e8c-835f-5d088a41f604">

Could you grant me the appropriate rights to open a PR in the repository? Thanks!

**Comment by tpluscode** [comment]
Released in v1.12
